project:
  type: website
  output-dir: docs
  
website:
  title: "" # keep empty
  site-url: "https://NedWitte_Travel.com/"
  search: 
    location: navbar
    type: overlay
  description: "Ned Travel blog"
  favicon: themockup.png
  navbar:
    left:
      - text: Articles #about the travel 
        href: index.qmd
      - text: Random maps library
        href: random_maps_library.qmd
      - text: Countries world map
        href: countries.qmd
      - text: World map with places
        href: worldmapplaces.qmd
      - text: Interesting external sources
        href: external_material.qmd
      
    right: 
      - text: About
        menu: 
          - text: Ned 
            href: about/Ned.qmd
          - text: ArrozcomNilius
            href: about/Nilius.qmd
      - icon: github
        href: https://github.com/NedWitte/ #will be changed
        
    search: true
    pinned: true 
        
format:
  html:
    theme: ocean
    fig-width: 12
    fig-height: 7
    css: 
       - html/style.scs
    code-link: true
    fontsize: 1em
    
editor: visual 

