project:
  type: website
  output-dir: docs
  
website:
  title: "" # keep empty
  search: 
    location: navbar
    type: overlay
  description: "Ned Travel blog"
  favicon: themockup.png
  navbar:
    left:
      - text: Articles #about the travel 
        href: index.qmd
      - text: Countries world map
        href: general.qmd
      - text: World map with places
        href: portfolio.qmd
      - text: Others
        href: dividend.qmd
      
    right: 
      - about/about.qmd
      - icon: github
        href: https://github.com/NedWitte/ #will be changed
        
    search: true
    pinned: true 
        
format:
  html:
    theme: ocean
    css: 
       - html/style.scs
    code-link: true
    fontsize: 1em
    
editor: visual 
comments: 
    hypothesis:
      theme: clean
      openSidebar: false
