project:
  type: website
  output-dir: docs
  
website:
  title: "" # keep empty
  search: 
    location: navbar
    type: overlay
  description: "Personal blog as test script"
  favicon: themockup.png
  navbar:
    left:
      - text: Stock analysis
        href: index.qmd
      - text: General analysis
        href: general.qmd
      - text: Ned Portfolio
        href: portfolio.qmd
      - text: Dividend income
        href: dividend.qmd
      
    right: 
      - about/about.qmd
      - icon: github
        href: https://github.com/NedWitte/ #will be changed
        
    search: true
    pinned: true 
        
format:
  html:
    theme: 
       - html/my-laterra.scss
    css: 
       - html/style.scs
    code-link: true
    fontsize: 1em
    
editor: visual 

