---
title: "My personal portfolio"
author: "JNW"
description: "stuff"
date: "2023-08-10"

---



```{r}
#| echo: false
#| output: false
#| include: false

# Load necessary libraries
library(ggplot2)
library(maps)

# Create a world map
world_map <- map_data("world")

# List of countries to highlight
highlighted_countries <- c("Germany", "France", "UK", "Portugal", "Spain", "USA", 
                           "Turkey", "Italy", "Slovakia", "Poland", "Netherlands",
                           "Switzerland", "Czech Republic", "Tunisia")

# Filter map data for the highlighted countries
highlighted_data <- world_map[world_map$region %in% highlighted_countries, ]

# Create the base world map plot
world_plot <- ggplot() +
  geom_polygon(data = world_map, aes(x = long, y = lat, group = group), fill = "lightgray", color = "black") +
  coord_fixed(ratio = 1.3) +
  theme_void()

# Highlight the specified countries
highlighted_plot <- world_plot +
  geom_polygon(data = highlighted_data, aes(x = long, y = lat, group = group), fill = "white", color = "black")

```
This is a map of the countries that I already visited in my life:

```{r}
#| echo: false
# Display the map
print(highlighted_plot)
```
Now this is a leaflet of major cities that I visited:

```{r}
#| echo: false
#| output: false
#| include: false

# Display the map
# Create a leaflet map centered around Germany
world_map <- leaflet() %>%
  setView(lng = 10.4515, lat = 51.1657, zoom = 1) %>%
  addTiles()  # Add the default OpenStreetMap tiles

#define cities
city_names <- c("Berlin", "Hannover", "Freiburg", "Porto", "Braga", 
                "Boston", "New York", "Barcelona", "Palma de Mallorca", "London", 
                "Köln")
latitudes = c(52.5200, 52.3759, 47.9990, 41.1579, 41.5337,
              42.3601, 40.7128, 41.3851, 39.5696,51.5074, 
              50.1109)
longitudes <-  c(13.4050, 9.7320, 7.8421, -8.6291, -8.4265,
                 -71.0589, -74.0060, 2.1734, 2.6502,-0.1278,
                 6.9603)

# Create a new DataFrame with the first 15 entries
cities <- data.frame(
  name = city_names,
  lat = latitudes,
  lon = longitudes
)


# Define custom marker icon with reduced size
customIcon <- makeIcon(
  iconUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/images/marker-icon.png",
  iconWidth = 10,  # Adjust the width as needed
  iconHeight = 15, # Adjust the height as needed
  iconAnchorX = 3,
  iconAnchorY = 5
)


# Add markers for each city
world_map <- world_map %>%
  addMarkers(
    data = cities,
    lat = ~lat,
    lng = ~lon,
    label = ~name,
    popup = ~name,
    icon = customIcon
  )

```

```{r}
#| echo: false
# Display the map
world_map
```
