---
title: "Germany map"
description: "test"
author: "JNW"
date: "2023"
date-format: "MMM D, YYYY"
---

**Some maps**

```{r}
#| echo: false
#| output: false
#| include: false
#| warning: false
#| message: false



#install.packages("WDI")
#install.packages("wbstats")
library(WDI)
library(tidyverse)
library(sf)
library(wbstats)
library(leaflet)


DEU0 <- read_sf("C:/Users/WITTEJ09/OneDrive - Pfizer/Documents/Quarto/KarambolageInvesting/NedTravel/data/shapefiles/DEU_SHP/DEU_adm0.shp")

DEU1 <- read_sf("C:/Users/WITTEJ09/OneDrive - Pfizer/Documents/Quarto/KarambolageInvesting/NedTravel/data/shapefiles/DEU_SHP/DEU_adm1.shp")

DEU2 <- read_sf("C:/Users/WITTEJ09/OneDrive - Pfizer/Documents/Quarto/KarambolageInvesting/NedTravel/data/shapefiles/DEU_SHP/DEU_adm2.shp")

DEU_roads <- read_sf("C:/Users/WITTEJ09/OneDrive - Pfizer/Documents/Quarto/KarambolageInvesting/NedTravel/data/shapefiles/DEU_SHP/DEU_roads.shp")

countries <- read_sf("C:/Users/WITTEJ09/OneDrive - Pfizer/Documents/Quarto/KarambolageInvesting/NedTravel/data/shapefiles/ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp")

pop_places <- read_sf("C:/Users/WITTEJ09/OneDrive - Pfizer/Documents/Quarto/KarambolageInvesting/NedTravel/data/shapefiles/ne_10m_populated_places/ne_10m_populated_places.shp")


```

```{r}
#| echo: false
#| output: false
#| include: false

 ggplot()+
  geom_sf(data = countries)+
  geom_sf(data = pop_places)+
  theme_void()

  
```

```{r}
#| echo: false
#| warning: false
#| message: false

 ggplot()+
  geom_sf(data = DEU0)+
  geom_sf(data = DEU1)+
  geom_sf(data = DEU2)+
  geom_sf(data = DEU_roads)
  theme_void()
 
```

\`\`\`
