---
title: "R&D Researchers per 1 million citizens"
description: "test with Andrew Heiss tutorial"
author: "JNW"
date: "2023"

---

**Some maps**

```{r}
#| echo: false
#| output: false
#| include: false
#| warning: false
#| message: false

#install.packages("WDI")
#install.packages("wbstats")
library(WDI)
library(tidyverse)
library(sf)
library(wbstats)
library(leaflet)

world_map <- read_sf("C:/Users/WITTEJ09/OneDrive - Pfizer/Documents/Quarto/KarambolageInvesting/NedTravel/data/shapefiles/shapefiles/ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp")

world_map <- world_map %>% 
  filter(ISO_A3 != "ATA")

#unemploy_inds<- wb_search("unemployment")

```

```{r}
#| echo: false
#| output: false
#| include: false

# Population, total
pop_data <- wb_data("SP.POP.SCIE.RD.P6", start_date = 2020, end_date = 2020)
pop_data <- pop_data %>% select(RD_per_mil = SP.POP.SCIE.RD.P6, iso3c)
pop_data <- pop_data%>% replace(is.na(.), 0)
pop_data$iso3c[pop_data$iso3c == "USA"] <- "4821"
pop_data$iso3c[pop_data$iso3c == "AUS"] <- "1500"

world_map <- world_map %>% 
              left_join(pop_data, by = c("ISO_A3" = "iso3c"))

#wb_search("SP.POP")

  
```

```{r}
#| echo: false
#| output: true

ggplot() + 
  geom_sf(data = world_map, 
          aes(fill = RD_per_mil),
          size = 0.25) +
  coord_sf(crs = st_crs("ESRI:54030")) +  # Robinson
  scale_fill_gradient(low = "grey100", high = "grey10") +
  labs(fill = "RD per one million citizen") +
  theme_void() +
  theme(legend.position = "bottom")

```

